### ISSUE TITLE
Link generation in dist files to other dependencies is not good

### ISSUE THREAD

**Issue by JoshK2** [teambit/bit#1972]
### Describe the bug

I imported a component that has a pop component as a dependency, and when I run the app, I get this error:
![image](https://user-images.githubusercontent.com/35892475/64162350-cedb7700-ce47-11e9-988a-4f6c87d5ca59.png)

This is the link in the button component fesm2015 folder:
```
import '@bit/joshk.cashmere-t1.pop/dist/pop/pop/popover.component';
import { PopModule } from '@bit/joshk.cashmere-t1.pop/dist/pop/pop/popover.module';
```
And if I chnge them to this, is good:
```
import '@bit/joshk.cashmere-t1.pop/dist/pop';
import { PopModule } from '@bit/joshk.cashmere-t1.pop/dist/pop';
```

### Steps to Reproduce

1. Create an empty angular app.
2. install this `npm i @angular/cdk`.
3. `bit import joshk.cashmere-t1/button` (it's private, I give you permission)
4. Edit the main app.module.ts to this:
```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppComponent } from './app.component';
import { ButtonModule } from '@bit/joshk.cashmere-t1.button';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    ButtonModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }

```

And this is the error you will get:
```
ERROR in ./components/button/dist/button/fesm2015/bit-button.js
Module not found: Error: Can't resolve '@bit/joshk.cashmere-t1.pop/dist/pop/pop/popover.component' in '/Users/yoshuakuttler/Documents/bit/importTesting/import-angular-components/components/button/dist/button/fesm2015'
ERROR in ./components/button/dist/button/fesm2015/bit-button.js
Module not found: Error: Can't resolve '@bit/joshk.cashmere-t1.pop/dist/pop/pop/popover.module' in '/Users/yoshuakuttler/Documents/bit/importTesting/import-angular-components/components/button/dist/button/fesm2015'
```

### Specifications

- Bit version: 14.2.6-dev.2
- Node version: v10.16.0
- Platform: macOS

**Comment by GiladShoham** [comment]
@davidfirst That's again something with the links for angular components with the compName / dist folder in the compiler.
I thought that we finish with all the bugs, but apparently there are few more.
In that case, there are I think 3 wrong links (after fixing the first you will see more).

**Comment by JoshK2** [comment]
I have a strange thing that happens, I exported with bit version 14.2.6-dev.2 to this collection https://bit.dev/joshk/cashmere-t1/button and it was not working, I tagged again all the components and export again and it's work!

So I want to try this thing in a new collection with version 14.2.6-dev.3, and it's not working
https://bit.dev/joshk/cashmere-t2/button 

I give yours permission to both collection, so you can import them to see the difference.
Another thing that I see is this stranger difference between the files name in fesm2015 folder:
![image](https://user-images.githubusercontent.com/35892475/64192999-95752c80-ce84-11e9-823e-f41741524aa0.png)
![image](https://user-images.githubusercontent.com/35892475/64193045-aa51c000-ce84-11e9-915a-836a3fdda331.png)

**Comment by JoshK2** [comment]
I checked it again to see if maybe it works, and it's not.
https://bit.dev/joshk/cashmere-t3/button

**Comment by davidfirst** [comment]
@qballer @GiladShoham , we fixed the original issue with the prefix of the component-name in the `dist` directory. However, in this case, it has the prefix twice.
See the error message in the description, it is unable to find `@bit/joshk.cashmere-t1.pop/dist/pop/pop/popover.component`. For some reason, looking into `pop` component, the dists of `pop` are in `pop/pop`.

**Comment by davidfirst** [comment]
The build of button t2 has been fixed in the PR above.
@JoshK2 , please try to re-create the button component from scratch (using the new dev version, v14.2.6-dev.4) and see if you get any errors.

**Comment by JoshK2** [comment]
Hey @davidfirst, I recreate this and it's still not working.
https://bit.dev/joshk/cashmere-t4/button

**Comment by itaymendel** [comment]
resolved as part of v15.

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
