### ISSUE TITLE
error compiling mdx

### ISSUE THREAD

**Issue by KutnerUri** [teambit/bit#4809]
Getting this error:

```
Failed to compile

Module parse failed: Assigning to rvalue (4:2)
File was processed with these loaders:
 * ../../../.bvm/versions/0.0.493/bit-0.0.493/node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js
You may need an additional loader to handle the result of these loaders.
| $RefreshSetup$(module.id);
| 
> ---
| labels: ['react', 'typescript', 'input', 'search']
| description: 'basic search bard'
```

It seems it's trying to load the mdx with the react fast refresh, before compiling it to JS.

I will investigate.

### Describe the bug
A clear and concise description of the issue.

### Steps to Reproduce
1. Open workspace
1. use `bit create` to make a new component, ie,

  `❯ bit create react-component ui/input/search-box`

1. bit start

--> get the error

### Screenshots, exceptions and logs
![Screen Shot 2021-08-25 at 18 38 09](https://user-images.githubusercontent.com/5400361/130821181-254b9640-34d0-468b-b511-2b59b151a4c4.png)

### Specifications
* Bit version: 0.0.493
* Workspace type: harmony
* Node version:
* npm / yarn version:
* Platform: MacOS

_for harmony workspace_

* relevant env: teambit.design/envs/react

**Comment by KutnerUri** [comment]
ah ok, it's not a blocker.
Just tried it in a new project, and it doesn't happen (😥 )

I'll keep a zip of the workspace and try it again..

**Comment by blankenshipd001** [comment]
I've also seen this error if you happen to have invalid syntax in your mdx file. I've found it useful to remove all content from the file with the exception of the top line and see if the error goes away. If it does you can start adding back a few lines at a time.

**Comment by KutnerUri** [comment]
this is likely to have been solved by #5067, so it should not happen again from v0.0.570 onwards.
The fix set `react-fast-refresh` loaders explicitly, making it's order preset, and should prevent incorrect loaders trying to parse markdown files.

repoen the issue if the problem resurfaces :)

**Comment by aweiu** [comment]
> 

`v0.0.638` the issue still exists:

![image](https://user-images.githubusercontent.com/15623620/151651573-bb1c2e27-d055-4e0d-a5e6-cf26c43585a6.png)

**Comment by KutnerUri** [comment]
interesting. why would it happen on yarn? 🤔 

also, I've noticed a distinction between `*.docs.mdx` and plain `*.mdx` files:
```bash
plugins-page/
  plugin-page.docs.mdx # <-- should work out of the box
  plugins-page.mdx # <-- needs env to be mdx
  index.ts
```

you can apply the mdx env by using this command:
```
❯ bit envs set my-component teambit.mdx/mdx 
```

**Comment by pkhodaveissi** [comment]
> interesting. why would it happen on yarn? 🤔 
> 
> 
> 
> also, I've noticed a distinction between `*.docs.mdx` and plain `*.mdx` files:
> 
> ```bash
> 
> plugins-page/
> 
>   plugin-page.docs.mdx # <-- should work out of the box
> 
>   plugins-page.mdx # <-- needs env to be mdx
> 
>   index.ts
> 
> ```
> 
> 
> 
> you can apply the mdx env by using this command:
> 
> ```
> 
> ❯ bit envs set my-component teambit.mdx/mdx 
> 
> ```

You need to run a _bit link_ after bit install if you're using yarn. But pnpm does that automatically I guess.

**Comment by KutnerUri** [comment]
interesting. @pkhodaveissi - can you open a new issue? @GiladShoham will handle
