### ISSUE TITLE
Workspace with react-env fails to start

### ISSUE THREAD

**Issue by PiTiLeZarD** [teambit/bit#7245]
Hey,

Part of my experiments with the new react-env, I'm just setting up my mui environment and all tools before moving all components across. For now, there's just the custom env with mui theme and theme provider, and a component theme-showcase showing plenty of mui related theme stuff (colours, fonts, buttons stuff like that).

Just as a start:
```
rm -Rf node_modules pnpm-lock.yaml && bit clear-cache && bit capsule delete && bvm update
bit install
```

So at this point I have a clean bill of health I assume.

bit start ends with this error:

```
ERROR in ./node_modules/.cache/bit/teambit.preview/preview/org.scope/envs/mui/compositions-1680649356289.js 4:0-204
Module not found: Error: Can't resolve '/Users/myUser/path/to/bit/node_modules/.bit_roots/org.scope_envs_mui/node_modules/@org/scope.helpers.theme-showcase/dist/theme-showcase.composition.js' in '/Users/myUser/path/to/bit/node_modules/.cache/bit/teambit.preview/preview/org.scope/envs/mui'
resolve '/Users/myUser/path/to/bit/node_modules/.bit_roots/org.scope_envs_mui/node_modules/@org/scope.helpers.theme-showcase/dist/theme-showcase.composition.js' in '/Users/myUser/path/to/bit/node_modules/.cache/bit/teambit.preview/preview/org.scope/envs/mui'
  No description file found in /Users/myUser/path/to/bit/node_modules/.cache/bit/teambit.preview/preview/org.scope/envs/mui or above
  root path /Users/myUser/path/to/bit
    No description file found in /Users/myUser/path/to/bit/Users/myUser/path/to/bit/node_modules/.bit_roots/org.scope_envs_mui/node_modules/@org/scope.helpers.theme-showcase/dist or above
    no extension
      /Users/myUser/path/to/bit/Users/myUser/path/to/bit/node_modules/.bit_roots/org.scope_envs_mui/node_modules/@org/scope.helpers.theme-showcase/dist/theme-showcase.composition.js doesn't exist
    .web.mjs
      /Users/myUser/path/to/bit/Users/myUser/path/to/bit/node_modules/.bit_roots/org.scope_envs_mui/node_modules/@org/scope.helpers.theme-showcase/dist/theme-showcase.composition.js.web.mjs doesn't exist
    .mjs
      /Users/myUser/path/to/bit/Users/myUser/path/to/bit/node_modules/.bit_roots/org.scope_envs_mui/node_modules/@org/scope.helpers.theme-showcase/dist/theme-showcase.composition.js.mjs doesn't exist
    .web.js
      /Users/myUser/path/to/bit/Users/myUser/path/to/bit/node_modules/.bit_roots/org.scope_envs_mui/node_modules/@org/scope.helpers.theme-showcase/dist/theme-showcase.composition.js.web.js doesn't exist
    .js
      /Users/myUser/path/to/bit/Users/myUser/path/to/bit/node_modules/.bit_roots/org.scope_envs_mui/node_modules/@org/scope.helpers.theme-showcase/dist/theme-showcase.composition.js.js doesn't exist
    .cjs
      /Users/myUser/path/to/bit/Users/myUser/path/to/bit/node_modules/.bit_roots/org.scope_envs_mui/node_modules/@org/scope.helpers.theme-showcase/dist/theme-showcase.composition.js.cjs doesn't exist
    .web.ts
      /Users/myUser/path/to/bit/Users/myUser/path/to/bit/node_modules/.bit_roots/org.scope_envs_mui/node_modules/@org/scope.helpers.theme-showcase/dist/theme-showcase.composition.js.web.ts doesn't exist
    .ts
      /Users/myUser/path/to/bit/Users/myUser/path/to/bit/node_modules/.bit_roots/org.scope_envs_mui/node_modules/@org/scope.helpers.theme-showcase/dist/theme-showcase.composition.js.ts doesn't exist
    .web.tsx
      /Users/myUser/path/to/bit/Users/myUser/path/to/bit/node_modules/.bit_roots/org.scope_envs_mui/node_modules/@org/scope.helpers.theme-showcase/dist/theme-showcase.composition.js.web.tsx doesn't exist
    .tsx
      /Users/myUser/path/to/bit/Users/myUser/path/to/bit/node_modules/.bit_roots/org.scope_envs_mui/node_modules/@org/scope.helpers.theme-showcase/dist/theme-showcase.composition.js.tsx doesn't exist
    .json
      /Users/myUser/path/to/bit/Users/myUser/path/to/bit/node_modules/.bit_roots/org.scope_envs_mui/node_modules/@org/scope.helpers.theme-showcase/dist/theme-showcase.composition.js.json doesn't exist
    .web.jsx
      /Users/myUser/path/to/bit/Users/myUser/path/to/bit/node_modules/.bit_roots/org.scope_envs_mui/node_modules/@org/scope.helpers.theme-showcase/dist/theme-showcase.composition.js.web.jsx doesn't exist
    .jsx
      /Users/myUser/path/to/bit/Users/myUser/path/to/bit/node_modules/.bit_roots/org.scope_envs_mui/node_modules/@org/scope.helpers.theme-showcase/dist/theme-showcase.composition.js.jsx doesn't exist
    .mdx
      /Users/myUser/path/to/bit/Users/myUser/path/to/bit/node_modules/.bit_roots/org.scope_envs_mui/node_modules/@org/scope.helpers.theme-showcase/dist/theme-showcase.composition.js.mdx doesn't exist
    .md
      /Users/myUser/path/to/bit/Users/myUser/path/to/bit/node_modules/.bit_roots/org.scope_envs_mui/node_modules/@org/scope.helpers.theme-showcase/dist/theme-showcase.composition.js.md doesn't exist
    as directory
      /Users/myUser/path/to/bit/Users/myUser/path/to/bit/node_modules/.bit_roots/org.scope_envs_mui/node_modules/@org/scope.helpers.theme-showcase/dist/theme-showcase.composition.js doesn't exist
  No description file found in /Users/myUser/path/to/bit/node_modules/.bit_roots/org.scope_envs_mui/node_modules/@org/scope.helpers.theme-showcase/dist or above
  no extension
    /Users/myUser/path/to/bit/node_modules/.bit_roots/org.scope_envs_mui/node_modules/@org/scope.helpers.theme-showcase/dist/theme-showcase.composition.js doesn't exist
  .web.mjs
    /Users/myUser/path/to/bit/node_modules/.bit_roots/org.scope_envs_mui/node_modules/@org/scope.helpers.theme-showcase/dist/theme-showcase.composition.js.web.mjs doesn't exist
  .mjs
    /Users/myUser/path/to/bit/node_modules/.bit_roots/org.scope_envs_mui/node_modules/@org/scope.helpers.theme-showcase/dist/theme-showcase.composition.js.mjs doesn't exist
  .web.js
    /Users/myUser/path/to/bit/node_modules/.bit_roots/org.scope_envs_mui/node_modules/@org/scope.helpers.theme-showcase/dist/theme-showcase.composition.js.web.js doesn't exist
  .js
    /Users/myUser/path/to/bit/node_modules/.bit_roots/org.scope_envs_mui/node_modules/@org/scope.helpers.theme-showcase/dist/theme-showcase.composition.js.js doesn't exist
  .cjs
    /Users/myUser/path/to/bit/node_modules/.bit_roots/org.scope_envs_mui/node_modules/@org/scope.helpers.theme-showcase/dist/theme-showcase.composition.js.cjs doesn't exist
  .web.ts
    /Users/myUser/path/to/bit/node_modules/.bit_roots/org.scope_envs_mui/node_modules/@org/scope.helpers.theme-showcase/dist/theme-showcase.composition.js.web.ts doesn't exist
  .ts
    /Users/myUser/path/to/bit/node_modules/.bit_roots/org.scope_envs_mui/node_modules/@org/scope.helpers.theme-showcase/dist/theme-showcase.composition.js.ts doesn't exist
  .web.tsx
    /Users/myUser/path/to/bit/node_modules/.bit_roots/org.scope_envs_mui/node_modules/@org/scope.helpers.theme-showcase/dist/theme-showcase.composition.js.web.tsx doesn't exist
  .tsx
    /Users/myUser/path/to/bit/node_modules/.bit_roots/org.scope_envs_mui/node_modules/@org/scope.helpers.theme-showcase/dist/theme-showcase.composition.js.tsx doesn't exist
  .json
    /Users/myUser/path/to/bit/node_modules/.bit_roots/org.scope_envs_mui/node_modules/@org/scope.helpers.theme-showcase/dist/theme-showcase.composition.js.json doesn't exist
  .web.jsx
    /Users/myUser/path/to/bit/node_modules/.bit_roots/org.scope_envs_mui/node_modules/@org/scope.helpers.theme-showcase/dist/theme-showcase.composition.js.web.jsx doesn't exist
  .jsx
    /Users/myUser/path/to/bit/node_modules/.bit_roots/org.scope_envs_mui/node_modules/@org/scope.helpers.theme-showcase/dist/theme-showcase.composition.js.jsx doesn't exist
  .mdx
    /Users/myUser/path/to/bit/node_modules/.bit_roots/org.scope_envs_mui/node_modules/@org/scope.helpers.theme-showcase/dist/theme-showcase.composition.js.mdx doesn't exist
  .md
    /Users/myUser/path/to/bit/node_modules/.bit_roots/org.scope_envs_mui/node_modules/@org/scope.helpers.theme-showcase/dist/theme-showcase.composition.js.md doesn't exist
  as directory
    /Users/myUser/path/to/bit/node_modules/.bit_roots/org.scope_envs_mui/node_modules/@org/scope.helpers.theme-showcase/dist/theme-showcase.composition.js doesn't exist
```

Another bit install ends with:
```
ENOENT: no such file or directory, open '/Users/myUser/path/to/bit/node_modules/.pnpm/file+org+envs+mui_zw7lwdafktctwamcwszm25ce5m/node_modules/@org/scope.envs.mui/dist/config/jest.config.js'
```

bit install again works that time. But the next bit start ends with tons of errors, I can't paste it all here but a few:

```
Module not found: Error: Can't resolve 'async_hooks' in '/Users/myUser/path/to/bit/node_modules/.pnpm/registry.npmjs.org+raw-body@2.5.1/node_modules/raw-body'
ModuleNotFoundError: Module not found: Error: Can't resolve 'async_hooks' in '/Users/myUser/path/to/bit/node_modules/.pnpm/registry.npmjs.org+raw-body@2.5.1/node_modules/raw-body'
    at /Users/myUser/path/to/bit/node_modules/.pnpm/registry.npmjs.org+webpack@5.51.1_esbuild@0.14.28/node_modules/webpack/lib/Compilation.js:1773:28
    at /Users/myUser/path/to/bit/node_modules/.pnpm/registry.npmjs.org+webpack@5.51.1_esbuild@0.14.28/node_modules/webpack/lib/NormalModuleFactory.js:811:13

Module not found: Error: Can't resolve 'node-sass' in '/Users/myUser/path/to/bit/node_modules/.pnpm/registry.npmjs.org+sass-loader@13.2.0_sass@1.56.1+webpack@5.51.1/node_modules/sass-loader/dist'
ModuleNotFoundError: Module not found: Error: Can't resolve 'node-sass' in '/Users/myUser/path/to/bit/node_modules/.pnpm/registry.npmjs.org+sass-loader@13.2.0_sass@1.56.1+webpack@5.51.1/node_modules/sass-loader/dist'
    at /Users/myUser/path/to/bit/node_modules/.pnpm/registry.npmjs.org+webpack@5.51.1_esbuild@0.14.28/node_modules/webpack/lib/Compilation.js:1773:28
    at /Users/myUser/path/to/bit/node_modules/.pnpm/registry.npmjs.org+webpack@5.51.1_esbuild@0.14.28/node_modules/webpack/lib/NormalModuleFactory.js:811:13
    at eval (eval at create (/Users/myUser/path/to/bit/node_modules/.pnpm/registry.npmjs.org+tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/myUser/path/to/bit/node_modules/.pnpm/registry.npmjs.org+webpack@5.51.1_esbuild@0.14.28/node_modules/webpack/lib/NormalModuleFactory.js:286:22
```

and then plenty of :

```
Critical dependency: the request of a dependency is an expression
ModuleDependencyWarning: Critical dependency: the request of a dependency is an expression
    at Compilation.reportDependencyErrorsAndWarnings (/Users/myUser/path/to/bit/node_modules/.pnpm/registry.npmjs.org+webpack@5.51.1_esbuild@0.14.28/node_modules/webpack/lib/Compilation.js:2591:23)
    at /Users/myUser/path/to/bit/node_modules/.pnpm/registry.npmjs.org+webpack@5.51.1_esbuild@0.14.28/node_modules/webpack/lib/Compilation.js:2204:10
```

That time I can see my compositions, but they're all blank.

My dependencies are as such:
```
        "policy": {
            "dependencies": {
                "@babel/runtime": "7.21.0",
                "@teambit/defender.eslint-linter": "0.0.8",
                "@teambit/defender.jest-tester": "0.0.8",
                "@teambit/defender.prettier-formatter": "0.0.5",
                "@teambit/dependencies.modules.packages-excluder": "0.0.70",
                "@teambit/mdx.ui.mdx-scope-context": "0.0.498",
                "@teambit/preview.react-preview": "0.0.28",
                "@teambit/react.mounter": "0.0.8",
                "@teambit/react.react-env": "0.0.52",
                "@teambit/typescript.typescript-compiler": "0.0.7",
                "core-js": "^3.30.0",
                "react": "^18.2.0",
                "react-dom": "^18.2.0",
                "react-router-dom": "6.10.0"
            },
            "peerDependencies": {}
        },
```

Any help would be gratefully received.

**Comment by pikulo-kama** [comment]
Are there some workarounds?

**Comment by PiTiLeZarD** [comment]
If you find one, I'll take it. My plan is to rebuild the workspace bit by bit (see what I did there? ;)) and figure out what step causes this, hoping for an epiphany regarding the solution. There's not much in there which is troubling. Or someone more knowledgable than me answers here whichever comes first.

**Comment by PiTiLeZarD** [comment]
Well actually, it's even worse than that:
```
❯ bit new react showcase --env teambit.react/react-env --default-scope org.scope
❯ cd showcase
❯ bit start
❯ bit create react helpers/theme-showcase
❯ bit start
```

And now it's broken already! this is without any custom anything

**Comment by PiTiLeZarD** [comment]
Ok I narrowed it down. There's 2 issues.

1) .bit_roots
The first one is with bit_roots but if I understand that well, they're working on that. And it goes away with 2 more `bit install` and then all good.

2) The second issue is a little more intricate.

If you have:
```
envs/mui
  -> lib/Test.tsx
  -> index.ts (export { Test } from './theme/test';)
helpers/theme-provider
  -> composition (import { Test } from "@org/scope.envs.mui")
```
And all hell breaks loose.

In my current react17 workspace, I have the env and the ThemeProvider in 2 separate components, but I had to compromise quite a lot in order to not have circular dependencies as the ThemeProvider needs to be of the env and let's say it's not ideal.

So either I'm not understanding what I'm supposed to do, or there's a bug somewhere where envs aren't treated as a component like all others.

Again, any help or nudge in the right direction will be gratefully received.

Happy easter everyone ;)

**Comment by itaymendel** [comment]
hi,

which version of Bit is installed? on `0.1.11` the root-components feature should be stable and working as intended.
you can remove the `rootComponents:true` from `workspace.jsonc`, this should revert to previous behavior of `bit install`.
root-components provides a much better isolation of components inside `node_modules`, making sure your builds will be more consistent.

as for the other issue, if you have `compA` configured with `envA`, and at the same time have `envA` depending on `compA` (say, grabbing the theme for compositions), you end up in a case of a circular dependency Bit can't resolve.
So in this case, if `compA` is your theme, you can use the base `react-env` as its config, as a solution.

**Comment by PiTiLeZarD** [comment]
I have the latest version of bit, and the scenario I described here with the latest of bit does get me in a bit_roots issue

> Well actually, it's even worse than that:
> 
> ```
> ❯ bit new react showcase --env teambit.react/react-env --default-scope org.scope
> ❯ cd showcase
> ❯ bit start
> ❯ bit create react helpers/theme-showcase
> ❯ bit start
> ```
> 
> And now it's broken already! this is without any custom anything

I know about the circular dependency, and that's not the situation I'm in, just to be clear, I have an envA exporting stuff, and a compA importing that stuff, and that's enough to break everything. I have recreated a brand new workspace. Added a file in the env (Test.tsx) export that through the env index.ts, then create a component in helpers/my-comp that imports that file and boom.

I will however try the workspace settings to see if that helps. Thanks

**Comment by GiladShoham** [comment]
Me and @zkochan will take this issue piece by piece to make sure this entire workflow is working properly.
It will take few days at least.
If you can provide a tar with a minimal workspace that reproduce these issues it will be very helpful.
Thanks

**Comment by PiTiLeZarD** [comment]
That would be my pleasure:

Step I took right now to generate this workspace:
```
clear caches and capsules and all that, bvm update just to be sure
❯ bit new react showcase --env teambit.react/react-env --default-scope org.scope
❯ cd showcase
❯ bit start -> works
❯ bit create react helpers/theme-showcase
❯ bit start -> broken
❯ bit install -> broken
❯ bit install -> works
❯ bit start -> works

create a env/src/example.tsx component
export through env/index.ts
use it in helpers/theme-showcase

❯ bit compile
❯ bit start -> real broken
```

The workspace is available here: https://drive.google.com/file/d/1bPIkNXRzKB5zWvbiz2lg9EiKfsoob3Cm/view?usp=sharing

**Comment by PiTiLeZarD** [comment]
@GiladShoham hey, no pressure but I'm just wondering if you had a chance to have a look at it? I'm curious to see if I'm doing something wrong of if there's a workaround.

**Comment by PiTiLeZarD** [comment]
@GiladShoham @zkochan Just keeping up with versions, I've updated bit to 0.1.27 and react-env to 0.0.58 and the problem persists

**Comment by PiTiLeZarD** [comment]
@GiladShoham @zkochan And again with bit 0.1.36 and react-env 0.0.63, are you guys working on this at all or should I just give up using the new environment. Are there people using it successfully? cuz from my side, anything I do just craps it.

**Comment by zkochan** [comment]
Do you still have the initial issue? We do work on issues. The last related issue we fixed was the first install after init and create. This was the PR: https://github.com/teambit/bit/pull/7369

**Comment by PiTiLeZarD** [comment]
@zkochan  Oh awesome, thanks for answering, I thought I was being ignored :)  And thanks for working on all these issues, much appreciated.

I'm not sure what you worked on, but that scenario I described a month ago still produces the same behaviour, with all the new versions.

Which is quite surprising to me, because it's the very basic thing I'm doing, creating a workspace, creating a component and it's already broken. Then I export a component from the env and it's completely out. I can't be the only one doing this, I'm wondering if I'm the only one experiencing the issue tho.

Also if you download this:
https://drive.google.com/file/d/1bPIkNXRzKB5zWvbiz2lg9EiKfsoob3Cm/view?usp=sharing

bit install, bit start will break.

I'll copy the steps to see what's broken and when here again just to be sure we speak about the same thing:
`
clear caches and capsules and all that, bvm update just to be sure
❯ bit new react showcase --env teambit.react/react-env --default-scope org.scope
❯ cd showcase
❯ bit start -> works
❯ bit create react helpers/theme-showcase
❯ bit start -> broken
❯ bit install -> broken
❯ bit install -> works
❯ bit start -> works

create a env/src/example.tsx component
export through env/index.ts
use it in helpers/theme-showcase

❯ bit compile
❯ bit start -> real broken
`

**Comment by zkochan** [comment]
It appears my fix is not in latest yet. Try to install bit CLI v0.1.40. With this version it doesn't break for me.

**Comment by GiladShoham** [comment]
In order to be able to install the nightly version that @zkochan mentioned you should run
`bvm config set RELEASE_TYPE nightly`

**Comment by rollymaduk** [comment]
Don't know if this is related,I have been getting this error once I try to create a workspace with default react env.
`Bit received an error loading teambit.react/react-env@0.0.63, due to the error:
"Cannot find module '@teambit/builder'".
This is required for the component: unknown
Please use the '--log=error' flag for the full error.
try running "bit install" to fix this issue`

**Comment by PiTiLeZarD** [comment]
@GiladShoham  so we must be miscommunicating I'm not sure.

I'm now on bit 0.1.42 with react-env 0.0.63.

In the scenario that I've expressed, only one step is fixed, I still can't get the thing to run.

```
clear caches and capsules and all that, bvm update just to be sure
❯ bit new react showcase --env teambit.react/react-env --default-scope org.scope
❯ cd showcase
❯ bit start -> works
❯ bit create react helpers/theme-showcase
❯ bit start -> still broken
❯ bit install 
```
now this bit install works when it didn't before, I don't need a second one, great! Look it would be better if the bit start wouldn't be broken to begin with yeah? we agree that this is fixing a symptom and not a disease but alright moving on, it works I'll take it.
```
❯ bit start -> works after the first bit install yay

create a env/src/example.tsx component
export that component through env/index.ts (export {Example} from "./src/example")
use it in helpers/theme-showcase (import {Example} from "@org/scope.envs.my-react-env" and just chuck <Example /> in the render)

❯ bit compile -> works
❯ bit start -> **still very broken**
```

I've alsow redownloaded my showcase.tgz, bit install, bit start and that's just plain broken, not sure what to do from there. I bothered my colleagues again, they've tried and same thing happens to them.

Are you telling me you download that file and `bit install && bit start` runs fine for you?

**Comment by FrankWangZY** [comment]
> Don't know if this is related,I have been getting this error once I try to create a workspace with default react env. `Bit received an error loading teambit.react/react-env@0.0.63, due to the error: "Cannot find module '@teambit/builder'". This is required for the component: unknown Please use the '--log=error' flag for the full error. try running "bit install" to fix this issue`
> 
> I ran the following command to get the errror above `bit new react faac-comp --env teambit.react/react-env --default-scope whitecanvas.faac-v2-components`

met similar problem,  I update pnpm to the latest version, everthing is fixed

**Comment by PiTiLeZarD** [comment]
@GiladShoham  @zkochan  Just pointing out that I've tried a fresh install of everything and then the same scenario as above, and it's still very much broken (bit 0.1.52 react-env 0.0.65)

Can we confirm that you have the same issues that I have so I know it's not just me? Are you still working on any of this? I'm desperate here...

**Comment by DmacMcgreg** [comment]
Hey @benjgil  @GiladShoham just wanted to say that I'm still getting this same error.

I've got : 
- my-react-env (came with the creation of the workspace_
- footer, header, form, menu components
- the components are using chakra-ui
- dependencies: 
- "@chakra-ui/react": "^2.7.1",
 "@emotion/react": "^11.11.1",
 "@emotion/styled": "^11.11.0",
 "framer-motion": "^10.12.22",
 "react-icons": "^4.10.1"
 
 Sometimes I'm getting "cannot resolve module @emotion/react"
 Other times I'm getting "cannot resolve module react-icons/fa" or react-icons/ai 
react-icons is a single package with folders like /ai or /io or /bs.

In my composition files I have  ( to theme the chakra components)
<ChakraProvider>
 <TheComponent />
</ChakraProvider>


Things I've tried to fix:
- deleting node modules
- bit install
- bit clear-cache
- putting all the dependencies under the hostDependencies of the preview environment under react-env-extension.bit-env.


Just have to say this is pretty frustrating, since it makes a basic bit environment pretty much impossible. I'm tryign to sell bit dev to our org, and this is our 3rd go at it, but every time we always run into big issues like this.

At one point I had the env stable and working, but as soon as I added another component, it broken again.

To be clear, this is the preview environment that is breaking. Is there not some way to turn off the preview env from failing the entire build? Since bit start works fine...

**Comment by GiladShoham** [comment]
First, I'm sorry to hear that you still have such issues.
I'm pretty sure that with some sync work we can solve this very quickly.
Some tips for better support : 
1. If you want to communicate over github, open a new issue. This one is closed so we might miss your messages. You can reference this one in the new one.
2. Make a thread on the technical questions on our slack. We usually respond faster there. Especially for support / help which is most likely not a bug that require code changes.
You can tag me and Benji there.

About your issue:
I would try to add them in the env.jsonc under peers (and maybe also in the host Dependencies)

There is also a way to disable the preview task of you want. But I would not recommend it. This should be easy to solve issue.

**Comment by DmacMcgreg** [comment]
Thanks @GiladShoham for the quick response.
Unfortunately the org decided not to go to bit for reasons like this, but I did manage to get it working, although without any particular reason.
I just deleted the last component I added, then put it back line-for-line the same and it work.
The only thing I did different was to tag the commit right after running the bit create command, but otherwise the code was the same.
I'm thinking it is a bug, since it did work eventually without any other changes. 
Hopefully you guys can fix it, since I do like bit. 

Looking forward to possibly using it in the future!

Just a suggestion, I appreciate that recently you have been adding a quickstart docs section, but the docs and the features in general are really quite complicated... From someone outside looking inwards, there is a lot of potential for it to be a great product, but the docs (and even the quickstart) seem really cluttered, and not so straightforward. 
There might be a way to abstract a way most of the complicated parts to make this sort of thing easier..

Anyways, best of luck! 
Cheers
